apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-y3wy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-y3wy
    app.kubernetes.io/part-of: tkrw-pr714-0075-0024-app
  name: devfile-sample-y3wy
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-y3wy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-y3wy
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0024-tenant/tkrw-pr714-0075-0024-app/devfile-sample-y3wy@sha256:54ce86fc39918bac5559ea9358a4386cd192c16c8f080d997f0ad071780a7c26
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
