apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-y3wy
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0024-tenant/tkrw-pr714-0075-0024-app/devfile-sample-y3wy@sha256:54ce86fc39918bac5559ea9358a4386cd192c16c8f080d997f0ad071780a7c26
        name: my-nodejs
        resources: {}
status: {}
